filebeat.inputs:
- type: log
  paths:
    - docker_logfile_path
    - docker_mount_logfile_path
  fields:
    namespace: "default"
    name: "io_kubernetes_container_name"
    pod_name: "io_kubernetes_pod_name"
filebeat.registry_file: /var/lib/docker/containers/id/registry
output.elasticsearch:
  hosts: ["localhost:9200"]
setup.kibana:
  host: "localhost:5601"

